#:kivy 1.11.1

<Toolbar@Widget>:
    StackLayout:
        pos: root.pos
        width: root.width
        height: root.height
        ToolbarButton:
            text: 'Save'
            on_release: root.controller.save()
        ToolbarButton:
            text: 'Run'
            on_release: root.controller.run_code()
        ToolbarButton:
            text: 'Quit'
            on_release: root.controller.quit()

<ToolbarButton@Button>:
    size_hint_x: 0.1
